from Aresta import Aresta
from Vertice import Vertice
from Grafo import Grafo

print("CODIGO DE GRAFO IMPLEMENTADO PELO PROFESSOR") # Milton - estrutura de dados 3 período
grafo = Grafo()
grafo.Add_Vertice('Ituiutaba')
grafo.Add_Vertice('Capinópolis')
grafo.Add_Vertice('Trevão')
grafo.Add_Vertice('Prata')
grafo.Add_Vertice('Monte Alegre')
grafo.Add_Vertice('Araguari')
grafo.Add_Vertice('Uberlândia')
grafo.Add_Aresta('Ituiutaba', 'Capinópolis', 30)
grafo.Add_Aresta('Ituiutaba', 'Trevão', 40)
grafo.Add_Aresta('Trevão', 'Prata', 70)
grafo.Add_Aresta('Trevão', 'Monte Alegre', 20)
grafo.Add_Aresta('Uberlândia', 'Prata', 70)
grafo.Add_Aresta('Uberlândia', 'Monte Alegre', 60)
grafo.Add_Aresta('Uberlândia', 'Araguari', 30)
grafo.Show_Vertices()
print("")


print("ALGORITMO DIJKSTRA IMPLEMENTADO A PARTIR DO CÓDIGO DE GRAFO")
print("Retorna um dicionário com as distâncias mínimas de todos os vértices a partir do vértice de origem. ")
print("--TREVÃO--")
distancias = grafo.dijkstra("Trevão")
print(distancias)
print("")
print("--ITUIUTABA--")
distancias = grafo.dijkstra("Ituiutaba")
print(distancias)
print("")
print("--CAPINÓPOLIS--")
distancias = grafo.dijkstra("Capinópolis")
print(distancias)
print("")
print("--UBERLANDIA--")
distancias = grafo.dijkstra("Uberlândia")
print(distancias)
print("")
print("--ARAGUARI--")
distancias = grafo.dijkstra("Araguari")
print(distancias)
print("")
print("--PRATA--")
distancias = grafo.dijkstra("Prata")
print(distancias)
print("")
print("--MONTE ALEGRE--")
distancias = grafo.dijkstra("Monte Alegre")
print(distancias)